[package]
name = "mithic-server"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "mithic-server"
path = "src/main.rs"

[dependencies]
mithic-config = { workspace = true }
mithic-api    = { workspace = true }
mithic-db     = { workspace = true }
mithic-federation = { workspace = true }
axum          = { workspace = true }
tokio         = { workspace = true }
tracing       = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow        = { workspace = true }
dotenvy       = { workspace = true }
mimalloc      = { workspace = true }
apalis        = { workspace = true }
apalis-redis  = { workspace = true }
futures       = { workspace = true }
tower         = { workspace = true }
